#!/bin/bash

# Get user params
echo "Enter new SSH port (not 22):"
read param_ssh_port
echo "Enter new hostname:"
read param_hostname
echo "Enter you IP:"
read param_ip_client
echo "Enter host IP:"
read param_ip_host
IFS=', ' read -r -a param_ip_client_arr <<< "$param_ip_client"

# Update & upgrade
apt-get update
apt-get upgrade
apt-get dist-upgrade

# Install dependencies
apt install -y curl fail2ban ufw knockd htop

# Set timezone
timedatectl set-timezone Europe/Moscow

# Clean MOTD
> /etc/motd

# Set hostname
echo "$param_hostname" > /etc/hostname
echo "127.0.0.1 localhost" > /etc/hosts
echo "$param_ip_host $param_hostname" >> /etc/hosts

# Set new SSH port
sed -i "s/#Port 22/Port $param_ssh_port/g" /etc/ssh/sshd_config

# Disable PING response and IPV6 protocol
echo "1" > /proc/sys/net/ipv4/icmp_echo_ignore_all
echo "net.ipv4.icmp_echo_ignore_all = 1" >> /etc/sysctl.conf
echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
sysctl -p

# Configure fail2ban
cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
curl "https://raw.githubusercontent.com/DeCrow/setMyDebian/main/fail2ban/jail.local" >> /etc/fail2ban/jail.local
wget -O "/etc/fail2ban/action.d/ssh-ufw.conf" "https://raw.githubusercontent.com/DeCrow/setMyDebian/main/fail2ban/ssh-ufw.conf"
sed -i 's/enabled = true/enabled = false/g' /etc/fail2ban/jail.d/defaults-debian.conf
systemctl restart fail2ban

# Configure firewall
sed -i 's/IPV6=yes/IPV6=no/g' /etc/default/ufw
sed -i '/ufw-before-input.*icmp/s/ACCEPT/DROP/g' /etc/ufw/before.rules
ufw default deny incoming
ufw default allow outgoing
for i in "${param_ip_client_arr[@]}"
do
   ufw allow from $i to any
done
ufw allow $param_ssh_port/tcp
echo "y" | ufw enable

# Configure knockd
wget -O /etc/knockd.conf 'https://raw.githubusercontent.com/DeCrow/setMyDebian/main/knockd/knockd.conf'
sed -i 's/ProtectSystem=full/ProtectSystem=true/g' /usr/lib/systemd/system/knockd.service
curl "https://raw.githubusercontent.com/DeCrow/setMyDebian/main/knockd/knockd.service" > /usr/lib/systemd/system/knockd.service
sed -i 's/START_KNOCKD=0/START_KNOCKD=1/g' /etc/default/knockd
systemctl enable systemd-networkd-wait-online.service
systemctl daemon-reload
systemctl enable knockd
service knockd start
