#!/bin/bash

# Get user params
read -p "Enter new SSH port (not 22): " param_ssh_port
read -p "Enter new hostname: " param_host_name

# Set params
param_host_ip=$(ip addr show |grep 'inet '|grep -v 127.0.0.1 |awk '{print $2}'| cut -d/ -f1)
param_client_ip=$(echo $SSH_CLIENT | awk '{ print $1}')
cGreen="\e[1;32m"
cYellow="\e[1;33m"
cEnd="\e[0m"

# Check params
echo "======================================="
echo -e "${cGreen}SSH port:  ${cYellow} ${param_ssh_port}${cEnd}"
echo -e "${cGreen}Host name: ${cYellow} ${param_host_name}${cEnd}"
echo -e "${cGreen}Host IP:   ${cYellow} ${param_host_ip}${cEnd}"
echo -e "${cGreen}Client IP: ${cYellow} ${param_client_ip}${cEnd}"
echo "======================================="

while true; do
    read -p "It is all OK? Can we proceed? [y|n]: " yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "It is all OK? Can we proceed? [y|n]: ";;
    esac
done

# Update & upgrade
apt update -y
apt upgrade -y
apt dist-upgrade -y

# Install dependencies
apt -qq -y install curl fail2ban ufw knockd htop

# Set timezone
timedatectl set-timezone Europe/Moscow

# Clean MOTD
> /etc/motd

# Set hostname
echo "${param_host_name}" > /etc/hostname
echo "127.0.0.1 localhost" > /etc/hosts
echo "${param_host_ip} ${param_host_name}" >> /etc/hosts

# Set new SSH port
sed -i "s/#Port 22/Port ${param_ssh_port}/g" /etc/ssh/sshd_config

# Disable PING response and IPV6 protocol
echo "1" > /proc/sys/net/ipv4/icmp_echo_ignore_all
echo "net.ipv4.icmp_echo_ignore_all = 1" >> /etc/sysctl.conf
echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
sysctl -p

# Configure fail2ban
cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
curl "https://raw.githubusercontent.com/DeCrow/setMyDebian/main/fail2ban/jail.local" >> /etc/fail2ban/jail.local
wget -O "/etc/fail2ban/action.d/ssh-ufw.conf" "https://raw.githubusercontent.com/DeCrow/setMyDebian/main/fail2ban/ssh-ufw.conf"
sed -i 's/enabled = true/enabled = false/g' /etc/fail2ban/jail.d/defaults-debian.conf
systemctl restart fail2ban

# Configure firewall
sed -i 's/IPV6=yes/IPV6=no/g' /etc/default/ufw
sed -i '/ufw-before-input.*icmp/s/ACCEPT/DROP/g' /etc/ufw/before.rules
ufw default deny incoming
ufw default allow outgoing
ufw allow from "${param_client_ip}" to any
ufw allow "${param_ssh_port}"/tcp
echo "y" | ufw enable

# Configure knockd
wget -O /etc/knockd.conf 'https://raw.githubusercontent.com/DeCrow/setMyDebian/main/knockd/knockd.conf'
sed -i 's/ProtectSystem=full/ProtectSystem=true/g' /usr/lib/systemd/system/knockd.service
curl "https://raw.githubusercontent.com/DeCrow/setMyDebian/main/knockd/knockd.service" > /usr/lib/systemd/system/knockd.service
sed -i 's/START_KNOCKD=0/START_KNOCKD=1/g' /etc/default/knockd
systemctl enable systemd-networkd-wait-online.service
systemctl daemon-reload
systemctl enable knockd
service knockd start
