#!/bin/bash 

# Get user params
echo "Enter name of folder in mnt:"
read param_mnt_name
echo "Enter your Yandex Disk login:"
read param_login
echo "Enter your Yandex Disk pass:"
read param_pass

# Set params
mnt_folder="/mnt/${param_mnt_name}"

# Update & upgrade
apt-get update
apt-get upgrade
apt-get dist-upgrade

# Hide interactive screens
export DEBIAN_FRONTEND=noninteractive

# Install
apt -y install davfs2
mkdir "${mnt_folder}"
echo "https://webdav.yandex.ru ${mnt_folder} davfs user,rw,nofail,_netdev 0 0" >> /etc/fstab
echo "https://webdav.yandex.ru ${param_login} ${param_pass}" >> /etc/davfs2/secrets
