#!/bin/bash 

# Get user params
read -p "Enter redirect URL: " param_url

# Update & upgrade
apt -y update
apt -y upgrade
apt -y dist-upgrade

# Install
apt -y install nginx
curl "https://raw.githubusercontent.com/DeCrow/setMyDebian/main/nginx/default" > /etc/nginx/sites-available/default
sed -i "s/REDIRECT_URL/http:\/\/${param_url}/g" "/etc/nginx/sites-available/default"
service nginx restart

# Open port for redirect
ufw allow 80/tcp