#!/bin/bash

apt update
apt -y install wget tar curl
mkdir -p /opt/grafana_mimir/conf
mkdir -p /tmp/mimir/rules
useradd --no-create-home --shell /bin/false grafana
cd /opt/grafana_mimir || exit
curl -s https://api.github.com/repos/grafana/mimir/releases/latest|grep browser_download_url|grep mimir-linux-amd64|grep -v sha|cut -d '"' -f 4|wget -qi - -O mimir
chown grafana:grafana -R /opt/grafana_mimir
chmod +x /opt/grafana_mimir/mimir
cd ~/ || exit

curl "https://raw.githubusercontent.com/DeCrow/setMyDebian/main/content/grafana_mimir/default.yaml" > /opt/grafana_mimir/conf/default.yaml
curl "https://raw.githubusercontent.com/DeCrow/setMyDebian/main/content/grafana_mimir/grafana_mimir.service" > /etc/systemd/system/grafana_mimir.service

# Now start and check the service is running
systemctl daemon-reload
systemctl start grafana_mimir
systemctl enable grafana_mimir
