#!/bin/bash

apt update
apt install -y software-properties-common gnupg2 curl
curl "https://packages.grafana.com/gpg.key" | apt-key add -
add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
apt update
apt install -y grafana
systemctl enable grafana-server
systemctl start grafana-server
