#!/bin/bash

# Create Prometheus system user / group
groupadd --system prometheus
useradd -s /sbin/nologin --system -g prometheus prometheus

# Create configuration and data directories
mkdir /var/lib/prometheus
for i in rules rules.d files_sd; do
  mkdir -p /etc/prometheus/${i}
done

# Download and Install Prometheus
apt update
apt -y install wget curl
mkdir -p /tmp/prometheus
cd /tmp/prometheus || exit
curl -s https://api.github.com/repos/prometheus/prometheus/releases/latest|grep browser_download_url|grep linux-amd64|cut -d '"' -f 4|wget -qi -
tar xvf prometheus*.tar.gz
cd prometheus*/ || exit
mv prometheus promtool /usr/local/bin/
mv prometheus.yml  /etc/prometheus/prometheus.yml
mv consoles/ console_libraries/ /etc/prometheus/
cd ~/ || exit
rm -rf /tmp/prometheus

# Create a Prometheus systemd Service unit file
curl "https://raw.githubusercontent.com/DeCrow/setMyDebian/main/content/prometheus/prometheus.service" > /etc/systemd/system/prometheus.service

# Change directory permissions.
for i in rules rules.d files_sd; do
  chown -R prometheus:prometheus /etc/prometheus/${i}
done
for i in rules rules.d files_sd; do
  chmod -R 775 /etc/prometheus/${i}
done
chown -R prometheus:prometheus /var/lib/prometheus/

# Reload systemd daemon and start the service
systemctl daemon-reload
systemctl enable prometheus
systemctl start prometheus
