#!/bin/bash

apt update
apt -y install wget tar curl
mkdir -p /tmp/node_exporter
cd /tmp/node_exporter || exit
curl -s https://api.github.com/repos/prometheus/node_exporter/releases/latest|grep browser_download_url|grep linux-amd64|cut -d '"' -f 4|wget -qi -
tar xvf node_exporter*.tar.gz
cd node_exporter*/ || exit
mv node_exporter /usr/local/bin/
cd ~/ || exit
rm -rf /tmp/node_exporter
useradd --no-create-home --shell /bin/false node_exporter
chown node_exporter:node_exporter /usr/local/bin/node_exporter
curl "https://raw.githubusercontent.com/DeCrow/setMyDebian/main/content/prometheus_exporter_node/node_exporter.service" > /etc/systemd/system/node_exporter.service

# Now start and check the service is running
systemctl daemon-reload
systemctl start node_exporter
systemctl enable node_exporter
